### ISSUE TITLE
have all the outputs be piped to less and have colour output

### ISSUE THREAD

**Issue by nikivdev** [ok-borg/borg#14]
Thank you for writing this tool, it is really incredible. 

One thing I like though is to have all the outputs be shown in less but I don't want to pipe every single query I make with borg to less manually myself, can I make it as default output somehow?

Also it would be nice to have some colour in these outputs.

Thank you for any help.

**Comment by crufter** [comment]
Hi, @nikitavoloboev!

Thank you for your kind words.

Both of those are good ideas. Making something 'default' requires some way to configure borg which does not exist yet but it will be implemented not too far away in the future.

I will also look into syntax highlighting!

Cheers

**Comment by crufter** [comment]
@nikitavoloboev it's in latest master. Do `borg pipeto less` to set it up. Let me know if it works for you.

**Comment by crufter** [comment]
Piping to less is implemented. In fact you can pipe to anything - a thing that does syntax highlight.
