### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by mcdado** [ok-borg/borg#18]
Hi there! I started to create a `brew` formula for borg, since it's easier for many to keep the package up to date. See https://github.com/Homebrew/homebrew-core/pull/5432

Problem is I don't know how to build go packages, and what are the Homebrew calls to do it properly. Anyway, I was hoping you could give a little help in the necessary steps…

**Comment by crufter** [comment]
Hi there!

Awesome idea, sure, gonna have a look at the build.

Thanks

**Comment by mcdado** [comment]
The formula builds now. The check that fails in the automatic build step is that the project is too recent (less than 30 days). Unless a maintainer gives a pass, the problem will be resolved on <strong><time datetime="2016-10-10T20:20:42Z">Oct. 10</time></strong>.

**Comment by crufter** [comment]
@mcdado Awesome and thanks!
