### ISSUE TITLE
Remove committed binaries in favour for releases

### ISSUE THREAD

**Issue by kitten** [ok-borg/borg#2]
Since the binaries are clogging up the repository and adding to the size over time, you should really consider removing them, before making any change.

This article lists the most important reason why: https://robinwinslow.uk/2013/06/11/dont-ever-commit-binary-files-to-git/

TLDR; All binaries that have ever been committed must all be fully downloaded when the repo is cloned.

I mean I could go on for long here :P https://twitter.com/tims/status/383118946909818880

But meh ;) Just use tags and Github releases

**Comment by crufter** [comment]
@philpl,

I totally agree, I will definitely look into this!

Thanks!
