### ISSUE TITLE
License of contributed items? Way to download a archive of all items?

### ISSUE THREAD

**Issue by olejorgenb** [ok-borg/borg#44]

**Comment by crufter** [comment]
@olejorgenb Do you mean the content the users add? We plan to be pretty open and laid back about most things, so I think it will be downloadable and reusable by other people.

Archiving is not a priority right now but once we implement the major things in the cooking (private entries, org management) we can do.

**Comment by olejorgenb** [comment]
Thanks, sounds good :) (Maybe best to be explicit about it though?)

**Comment by crufter** [comment]
@olejorgenb Yeah, I will look up how one goes about licensing data and implement the necessary changes.
