### ISSUE TITLE
No available formula with the name "borg"

### ISSUE THREAD

**Issue by pkuczynski** [ok-borg/borg#50]
`brew install borg` display `Error: No available formula with the name "borg"`

**Comment by jeremyletang** [comment]
hey, I just tried to `brew info borg`, `brew search borg`, and both list and give informations about borg. Maybe you need to run `brew update` in order to update your local list of brew formulas ?

**Comment by crufter** [comment]
If that's the case, @jeremyletang we should include `brew update` in the readme.

**Comment by jeremyletang** [comment]
@crufter , haha if you want, but I'm not sure the goal of our readme is to cover brew documentation ?

**Comment by crufter** [comment]
Can't hurt, it's one line, and if it avoids problems, a line well spent

**Comment by pkuczynski** [comment]
Strange. I did run `brew update`, however 

```
$ brew --version
Homebrew 1.1.9-32-g73df504
Homebrew/homebrew-core (git revision a5307; last commit 2016-09-20)
```

So I have latest brew. just `brew-core` does not seem to get updated. Odd.

**Comment by jeremyletang** [comment]
```
$ brew --version
Homebrew 1.1.9
Homebrew/homebrew-core (git revision 4bbfe; last commit 2017-02-07)
```

here is my brew version. it's odd yeah.

**Comment by pkuczynski** [comment]
Mae culpa, had homebrew-core set for a branch. Now it all works, thanks!
