### ISSUE TITLE
cannot execute binary file: exec format error

### ISSUE THREAD

**Issue by ghost** [ok-borg/borg#53]
So i've been trying to intall borg on my mint, and despite my different tries on different releases it never works ^^ always the same message. If any one has a way to fix I'd be very thankfull

**Comment by jeremyletang** [comment]
Mint is a debian based gnu/linux right ?
which binary did you try ? one of those:
- borg_linux_386
- borg_linux_amd64

**Comment by ghost** [comment]
Yes, mint is Debian based, so just like I told before I tried the installation with 386/amd64,

wget https://github.com/ok-borg/borg/releases/download/v0.0.**2**/borg_linux_**amd64(or 386)** -O /usr/local/bin/borg

then 

chmod 755 /usr/local/bin/borg  , so just like its written on the Install section.

So when I try withe amd64 installation I get the same error as before, BUT when I try with the 386 release.. I get a " panic: user: Current not implemented on linux/386"

followed by a badass message: 

goroutine 1 [running]:
github.com/crufter/borg/conf.init.1()
	/Users/crufter/go/src/github.com/crufter/borg/conf/conf.go:36 +0x58
github.com/crufter/borg/conf.init()
	/Users/crufter/go/src/github.com/crufter/borg/conf/conf.go:72 +0x1b2
github.com/crufter/borg/commands.init()
	/Users/crufter/go/src/github.com/crufter/borg/commands/worked.go:80 +0x4d
main.init()
	/Users/crufter/go/src/github.com/crufter/borg/main.go:39 +0x43

so actually I'm noob enough to not understand a thing here ^^

**Comment by crufter** [comment]
"Current not implemented on linux/386" this is really weird, gonna have a look at this @worship-john

**Comment by ghost** [comment]
Ok, anything I should do to help ?

**Comment by crufter** [comment]
Ok this thread says the package `os/user` needs `cgo`, https://github.com/golang/go/issues/14625

I will see if there is a way to fix this, by compiling in an other way.

**Comment by ghost** [comment]
Ok so I read several times the tread to try understanding but a recap wont hurt anyone, so I have to:

- download the linux prebuilt binary (i'll google that to find what to download)
- extract the pkg/linux_386 directory
- put it under your GOROOT/ pkg ( okay I actually didn't undestand this part)

right ?

**Comment by crufter** [comment]
@worship-john I believe that's correct, yes. Will look wether there is an easier way, it shouldn't be this painful.

**Comment by ghost** [comment]
Ok so I tried to solve this, google a lot but no success ... I actually don't know how to proceed ^^

**Comment by crufter** [comment]
@worship-john Perhaps install docker and try the dockerised version: https://github.com/juhofriman/borg-docker
