### ISSUE TITLE
Error while making request

### ISSUE THREAD

**Issue by phineas0fog** [ok-borg/borg#54]
Hello :)
When I use *borg "get ip"*, for example, the command return **1**, with the following output : 
`Error while making request: Get http://borg.crufter.com:9992/v1/query?l=5&p=false&q=get+ip: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
`
Then, I try to ping *borg.crufter.com* and the website seems be down... Is there a solution ? :)

Thanks, and big up for your idea, she's very very very nice !

**Comment by crufter** [comment]
@phineas0fog this was due to an old DNS entry for the old address. Should be fixed now. Cheers
