### ISSUE TITLE
Website unusable

### ISSUE THREAD

**Issue by vince2010091** [ok-borg/borg#55]
Hello, 
The web site https://ok-b.org/ is not working, any search return nothing
Regards

**Comment by crufter** [comment]
@vince2010091 It works on my end, can you check the javascript consol and see what it prints?

**Comment by xiorcal** [comment]
I got a 403 on https://ok-b.org:9993/v1/query?q=list+files&t= too
(trying to access https://ok-b.org/s/list%20files)

**Comment by jeremyletang** [comment]
Are you logged in, or using borg as a non-logged user ?

**Comment by xiorcal** [comment]
non logged

**Comment by crufter** [comment]
I logged out, and I can still hit https://ok-b.org:9993/v1/query?q=list+files&t= fine.

I checked all whitelisted IPs for certain ports, removed mine now and it still works. Not sure what is going on exactly.

Can you copy the curl from your browser please @xiorcal

**Comment by xiorcal** [comment]
it's probably related to corporate firewall, i'll try at home

**Comment by jeremyletang** [comment]
Or print here the complete output of this curl:
`curl -v https://ok-b.org:9993/v1/query\?q\=list+files\&t\=`

**Comment by xiorcal** [comment]
```
curl -v https://ok-b.org:9993/v1/query\?q\=list+files\&t\=
* Hostname was NOT found in DNS cache
*   Trying local-ip
* Connected to proxyhost () port xxx (#0)
* Establish HTTP proxy tunnel to ok-b.org:9993
> CONNECT ok-b.org:9993 HTTP/1.1
> Host: ok-b.org:9993
> User-Agent: curl/7.35.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.0 403 Forbidden
< Server: squid
< Date: Wed, 01 Mar 2017 17:10:45 GMT
< Content-Type: text/html
< Content-Length: 1072
< Expires: Wed, 01 Mar 2017 17:10:45 GMT
< X-Squid-Error: ERR_ACCESS_DENIED 0
< X-Cache: MISS from some.company.server
< X-Cache-Lookup: NONE from some.company.server
< Via: 1.0 some.company.server (squid)
< Proxy-Connection: close
< 
* Received HTTP code 403 from proxy after CONNECT
* Connection #0 to host proxyhost left intact
curl: (56) Received HTTP code 403 from proxy after CONNECT
```

so yeah it looks like it's from the company proxy

**Comment by crufter** [comment]
Ok we are going to create a subdomain instead of using a port, I think that's the problem here.

**Comment by vince2010091** [comment]
You're God damn right.
![9993 restricted](https://cloud.githubusercontent.com/assets/1927789/23501631/de17a4bc-ff34-11e6-9618-8a8f5edb58aa.png)
