### ISSUE TITLE
Version 0.0.2 does not work on OSX

### ISSUE THREAD

**Issue by Marc66** [ok-borg/borg#56]
Version 0.0.1 runs fine but when I download and try version 0.0.2 on my Mac running El Capitan, I get the following:
panic: user: Current not implemented on darwin/amd64

goroutine 1 [running]:
github.com/crufter/borg/conf.init.1()
	/Users/crufter/go/src/github.com/crufter/borg/conf/conf.go:36 +0x62
github.com/crufter/borg/conf.init()
	/Users/crufter/go/src/github.com/crufter/borg/conf/conf.go:72 +0x1e8
github.com/crufter/borg/commands.init()
	/Users/crufter/go/src/github.com/crufter/borg/commands/worked.go:80 +0x4a
main.init()
	/Users/crufter/go/src/github.com/crufter/borg/main.go:39 +0x40

**Comment by crufter** [comment]
So even search fails? @Marc66

**Comment by Marc66** [comment]
I get this message whenever I launch the tool. Even launching without any parameters gives me this error

**Comment by crufter** [comment]
@Marc66 I see. We are going to fix this
